language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pipenv
  # - pipenv install --system
  - pipenv sync
  # - virtualenv env
  # - source env/bin/activate
  # - pipenv install
# command to run tests
script:
  - python check_update.py